# \file
# \brief Callbacks, Attributes and Attribute Values definitions.
# Avoid using these definitions. Use the strings instead.
#
# See Copyright Notice in iup.h
#


#  Deprecated definitions  #
#  Avoid using these definitions. Use the strings instead.  #
#  Define __IUPDEF_H to avoid the inclusion of this header  #

constant RUN = "RUN"
constant ENGLISH = "ENGLISH"
constant PORTUGUESE = "PORTUGUESE"
constant SBH = "SBH"
constant SBV = "SBV"

##########################################################################
#                             Callbacks                                  #
##########################################################################

constant DEFAULT_ACTION = "DEFAULT_ACTION"
constant IDLE_ACTION = "IDLE_ACTION"

constant ACTION = "ACTION"
constant GETFOCUS_CB = "GETFOCUS_CB"
constant KILLFOCUS_CB = "KILLFOCUS_CB"
constant K_ANY = "K_ANY"
constant KEYPRESS_CB = "KEYPRESS_CB"
constant HELP_CB = "HELP_CB"

constant SCROLL_CB = "SCROLL_CB"
constant RESIZE_CB = "RESIZE_CB"
constant MOTION_CB = "MOTION_CB"
constant BUTTON_CB = "BUTTON_CB"
constant ENTERWINDOW_CB = "ENTERWINDOW_CB"
constant LEAVEWINDOW_CB = "LEAVEWINDOW_CB"
constant WHEEL_CB = "WHEEL_CB"

constant MASK_CB = "MASK_CB"
constant OPEN_CB = "OPEN_CB"
constant HIGHLIGHT_CB = "HIGHLIGHT_CB"
constant MENUCLOSE_CB = "MENUCLOSE_CB"

constant MAP_CB = "MAP_CB"
constant CLOSE_CB = "CLOSE_CB"
constant SHOW_CB = "SHOW_CB"

constant DROPFILES_CB = "DROPFILES_CB"
constant WOM_CB = "WOM_CB"

##########################################################################
#                             Attributes                                 #
##########################################################################

constant DIRECTION = "DIRECTION"
constant ACTIVE = "ACTIVE"
constant BGCOLOR = "BGCOLOR"
constant FRAMECOLOR = "FRAMECOLOR"
constant FGCOLOR = "FGCOLOR"
constant COLOR = "COLOR"
constant WID = "WID"
constant SIZE = "SIZE"
constant RASTERSIZE = "RASTERSIZE"
constant TITLE = "TITLE"
constant VALUE = "VALUE"
constant VISIBLE = "VISIBLE"
constant FONT = "FONT"
constant TIP = "TIP"
constant EXPAND = "EXPAND"
constant SEPARATOR = "SEPARATOR"

constant HOTSPOT = "HOTSPOT"
constant HEIGHT = "HEIGHT"
constant WIDTH = "WIDTH"

constant KEY = "KEY"

constant MULTIPLE = "MULTIPLE"
constant DROPDOWN = "DROPDOWN"
constant VISIBLE_ITEMS = "VISIBLE_ITEMS"

constant MARGIN = "MARGIN"
constant GAP = "GAP"
constant ALIGNMENT = "ALIGNMENT"

constant IMAGE = "IMAGE"
constant IMINACTIVE = "IMINACTIVE"
constant IMPRESS = "IMPRESS"
constant WIN_SAVEBITS = "WIN_SAVEBITS"

constant NC = "NC"
constant MASK = "MASK"

constant APPEND = "APPEND"
constant BORDER = "BORDER"

constant CARET = "CARET"
constant SELECTION = "SELECTION"
constant SELECTEDTEXT = "SELECTEDTEXT"
constant INSERT = "INSERT"

constant CONID = "CONID"
constant CURSOR = "CURSOR"

constant ICON = "ICON"
constant MENUBOX = "MENUBOX"
constant MINBOX = "MINBOX"
constant MAXBOX = "MAXBOX"
constant RESIZE = "RESIZE"
constant MENU = "MENU"
constant STARTFOCUS = "STARTFOCUS"
constant PARENTDIALOG = "PARENTDIALOG"
constant SHRINK = "SHRINK"
constant DEFAULTENTER = "DEFAULTENTER"
constant DEFAULTESC = "DEFAULTESC"
constant X = "X"
constant Y = "Y"
constant TOOLBOX = "TOOLBOX"
constant CONTROL = "CONTROL"
constant READONLY = "READONLY"

constant SCROLLBAR = "SCROLLBAR"
constant POSY = "POSY"
constant POSX = "POSX"
constant DX = "DX"
constant DY = "DY"
constant XMAX = "XMAX"
constant XMIN = "XMIN"
constant YMAX = "YMAX"
constant YMIN = "YMIN"

constant RED = "255 0 0"
constant GREEN = "0 255 0"
constant BLUE = "0 0 255"

constant MIN = "MIN"
constant MAX = "MAX"

constant TIME = "TIME"
constant DRAG = "DRAG"
constant DROP = "DROP"
constant REPAINT = "REPAINT"
constant TOPMOST = "TOPMOST"
constant CLIPCHILDREN = "CLIPCHILDREN"

constant DIALOGTYPE = "DIALOGTYPE"
constant FILE = "FILE"
constant MULTIPLEFILES = "MULTIPLEFILES"
constant FILTER = "FILTER"
constant FILTERUSED = "FILTERUSED"
constant FILTERINFO = "FILTERINFO"
constant EXTFILTER = "EXTFILTER"
constant DIRECTORY = "DIRECTORY"
constant ALLOWNEW = "ALLOWNEW"
constant NOOVERWRITEPROMPT = "NOOVERWRITEPROMPT"
constant NOCHANGEDIR = "NOCHANGEDIR"
constant FILEEXIST = "FILEEXIST"
constant STATUS = "STATUS"

constant LOCKLOOP = "LOCKLOOP"
constant SYSTEM = "SYSTEM"
constant DRIVER = "DRIVER"
constant SCREENSIZE = "SCREENSIZE"
constant SYSTEMLANGUAGE = "SYSTEMLANGUAGE"
constant COMPUTERNAME = "COMPUTERNAME"
constant USERNAME = "USERNAME"

constant OPEN = "OPEN"
constant SAVE = "SAVE"
constant DIR = "DIR"

constant HORIZONTAL = "HORIZONTAL"
constant VERTICAL = "VERTICAL"

##########################################################################
#                        Attribute Values                                #
##########################################################################

constant YES = "YES"
constant NO = "NO"
constant ON = "ON"
constant OFF = "OFF"

constant ACENTER = "ACENTER"
constant ALEFT = "ALEFT"
constant ARIGHT = "ARIGHT"
constant ATOP = "ATOP"
constant ABOTTOM = "ABOTTOM"

constant NORTH = "NORTH"
constant SOUTH = "SOUTH"
constant WEST = "WEST"
constant EAST = "EAST"
constant NE = "NE"
constant SE = "SE"
constant NW = "NW"
constant SW = "SW"

constant FULLSCREEN = "FULLSCREEN"
constant FULL = "FULL"
constant HALF = "HALF"
constant THIRD = "THIRD"
constant QUARTER = "QUARTER"
constant EIGHTH = "EIGHTH"

constant ARROW = "ARROW"
constant BUSY = "BUSY"
constant RESIZE_N = "RESIZE_N"
constant RESIZE_S = "RESIZE_S"
constant RESIZE_E = "RESIZE_E"
constant RESIZE_W = "RESIZE_W"
constant RESIZE_NE = "RESIZE_NE"
constant RESIZE_NW = "RESIZE_NW"
constant RESIZE_SE = "RESIZE_SE"
constant RESIZE_SW = "RESIZE_SW"
constant MOVE = "MOVE"
constant HAND = "HAND"
constant NONE = "NONE"
constant IUP = "IUP"
constant CROSS = "CROSS"
constant PEN = "PEN"
constant TEXT = "TEXT"
constant RESIZE_C = "RESIZE_C"
constant OPENHAND = "OPENHAND"

###################
#  Fonts         #
###################

constant HELVETICA_NORMAL_8 = "HELVETICA_NORMAL_8"
constant HELVETICA_ITALIC_8 = "HELVETICA_ITALIC_8"
constant HELVETICA_BOLD_8 = "HELVETICA_BOLD_8"
constant HELVETICA_NORMAL_10 = "HELVETICA_NORMAL_10"
constant HELVETICA_ITALIC_10 = "HELVETICA_ITALIC_10"
constant HELVETICA_BOLD_10 = "HELVETICA_BOLD_10"
constant HELVETICA_NORMAL_12 = "HELVETICA_NORMAL_12"
constant HELVETICA_ITALIC_12 = "HELVETICA_ITALIC_12"
constant HELVETICA_BOLD_12 = "HELVETICA_BOLD_12"
constant HELVETICA_NORMAL_14 = "HELVETICA_NORMAL_14"
constant HELVETICA_ITALIC_14 = "HELVETICA_ITALIC_14"
constant HELVETICA_BOLD_14 = "HELVETICA_BOLD_14"
constant COURIER_NORMAL_8 = "COURIER_NORMAL_8"
constant COURIER_ITALIC_8 = "COURIER_ITALIC_8"
constant COURIER_BOLD_8 = "COURIER_BOLD_8"
constant COURIER_NORMAL_10 = "COURIER_NORMAL_10"
constant COURIER_ITALIC_10 = "COURIER_ITALIC_10"
constant COURIER_BOLD_10 = "COURIER_BOLD_10"
constant COURIER_NORMAL_12 = "COURIER_NORMAL_12"
constant COURIER_ITALIC_12 = "COURIER_ITALIC_12"
constant COURIER_BOLD_12 = "COURIER_BOLD_12"
constant COURIER_NORMAL_14 = "COURIER_NORMAL_14"
constant COURIER_ITALIC_14 = "COURIER_ITALIC_14"
constant COURIER_BOLD_14 = "COURIER_BOLD_14"
constant TIMES_NORMAL_8 = "TIMES_NORMAL_8"
constant TIMES_ITALIC_8 = "TIMES_ITALIC_8"
constant TIMES_BOLD_8 = "TIMES_BOLD_8"
constant TIMES_NORMAL_10 = "TIMES_NORMAL_10"
constant TIMES_ITALIC_10 = "TIMES_ITALIC_10"
constant TIMES_BOLD_10 = "TIMES_BOLD_10"
constant TIMES_NORMAL_12 = "TIMES_NORMAL_12"
constant TIMES_ITALIC_12 = "TIMES_ITALIC_12"
constant TIMES_BOLD_12 = "TIMES_BOLD_12"
constant TIMES_NORMAL_14 = "TIMES_NORMAL_14"
constant TIMES_ITALIC_14 = "TIMES_ITALIC_14"
constant TIMES_BOLD_14 = "TIMES_BOLD_14"

##########################################################################
#                            Keys                                        #
##########################################################################

constant K_exclam = "K_exclam"
constant K_quotedbl = "K_quotedbl"
constant K_numbersign = "K_numbersign"
constant K_dollar = "K_dollar"
constant K_percent = "K_percent"
constant K_ampersand = "K_ampersand"
constant K_quoteright = "K_quoteright"
constant K_parentleft = "K_parentleft"
constant K_parentright = "K_parentright"
constant K_asterisk = "K_asterisk"
constant K_plus = "K_plus"
constant K_comma = "K_comma"
constant K_minus = "K_minus"
constant K_period = "K_period"
constant K_slash = "K_slash"
constant K_0 = "K_0"
constant K_1 = "K_1"
constant K_2 = "K_2"
constant K_3 = "K_3"
constant K_4 = "K_4"
constant K_5 = "K_5"
constant K_6 = "K_6"
constant K_7 = "K_7"
constant K_8 = "K_8"
constant K_9 = "K_9"
constant K_colon = "K_colon"
constant K_semicolon = "K_semicolon "
constant K_less = "K_less"
constant K_equal = "K_equal"
constant K_greater = "K_greater"
constant K_question = "K_question"
constant K_at = "K_at"
constant K_A = "K_A"
constant K_B = "K_B"
constant K_C = "K_C"
constant K_D = "K_D"
constant K_E = "K_E"
constant K_F = "K_F"
constant K_G = "K_G"
constant K_H = "K_H"
constant K_I = "K_I"
constant K_J = "K_J"
constant K_K = "K_K"
constant K_L = "K_L"
constant K_M = "K_M"
constant K_N = "K_N"
constant K_O = "K_O"
constant K_P = "K_P"
constant K_Q = "K_Q"
constant K_R = "K_R"
constant K_S = "K_S"
constant K_T = "K_T"
constant K_U = "K_U"
constant K_V = "K_V"
constant K_W = "K_W"
constant K_X = "K_X"
constant K_Y = "K_Y"
constant K_Z = "K_Z"
constant K_bracketleft = "K_bracketleft"
constant K_backslash = "K_backslash"
constant K_bracketright = "K_bracketright"
constant K_circum = "K_circum"
constant K_underscore = "K_underscore"
constant K_quoteleft = "K_quoteleft"
constant K_a = "K_a"
constant K_b = "K_b"
constant K_c = "K_c"
constant K_d = "K_d"
constant K_e = "K_e"
constant K_f = "K_f"
constant K_g = "K_g"
constant K_h = "K_h"
constant K_i = "K_i"
constant K_j = "K_j"
constant K_k = "K_k"
constant K_l = "K_l"
constant K_m = "K_m"
constant K_n = "K_n"
constant K_o = "K_o"
constant K_p = "K_p"
constant K_q = "K_q"
constant K_r = "K_r"
constant K_s = "K_s"
constant K_t = "K_t"
constant K_u = "K_u"
constant K_v = "K_v"
constant K_w = "K_w"
constant K_x = "K_x"
constant K_y = "K_y"
constant K_z = "K_z"
constant K_braceleft = "K_braceleft"
constant K_bar = "K_bar"
constant K_braceright = "K_braceright"
constant K_tilde = "K_tilde"

constant K_cA = "K_cA"
constant K_cB = "K_cB"
constant K_cC = "K_cC"
constant K_cD = "K_cD"
constant K_cE = "K_cE"
constant K_cF = "K_cF"
constant K_cG = "K_cG"
constant K_cJ = "K_cJ"
constant K_cK = "K_cK"
constant K_cL = "K_cL"
constant K_cN = "K_cN"
constant K_cO = "K_cO"
constant K_cP = "K_cP"
constant K_cQ = "K_cQ"
constant K_cR = "K_cR"
constant K_cS = "K_cS"
constant K_cT = "K_cT"
constant K_cU = "K_cU"
constant K_cV = "K_cV"
constant K_cW = "K_cW"
constant K_cX = "K_cX"
constant K_cY = "K_cY"
constant K_cZ = "K_cZ"
constant K_mA = "K_mA"
constant K_mB = "K_mB"
constant K_mC = "K_mC"
constant K_mD = "K_mD"
constant K_mE = "K_mE"
constant K_mF = "K_mF"
constant K_mG = "K_mG"
constant K_mH = "K_mH"
constant K_mI = "K_mI"
constant K_mJ = "K_mJ"
constant K_mK = "K_mK"
constant K_mL = "K_mL"
constant K_mM = "K_mM"
constant K_mN = "K_mN"
constant K_mO = "K_mO"
constant K_mP = "K_mP"
constant K_mQ = "K_mQ"
constant K_mR = "K_mR"
constant K_mS = "K_mS"
constant K_mT = "K_mT"
constant K_mU = "K_mU"
constant K_mV = "K_mV"
constant K_mW = "K_mW"
constant K_mX = "K_mX"
constant K_mY = "K_mY"
constant K_mZ = "K_mZ"
constant K_BS = "K_BS"
constant K_TAB = "K_TAB"
constant K_CR = "K_CR"
constant K_SP = "K_SP"
constant K_ESC = "K_ESC"
constant K_sCR = "K_sCR"
constant K_sTAB = "K_sTAB"
constant K_cTAB = "K_cTAB"
constant K_mTAB = "K_mTAB"
constant K_HOME = "K_HOME"
constant K_UP = "K_UP"
constant K_PGUP = "K_PGUP"
constant K_LEFT = "K_LEFT"
constant K_RIGHT = "K_RIGHT"
constant K_END = "K_END"
constant K_DOWN = "K_DOWN"
constant K_PGDN = "K_PGDN"
constant K_MIDDLE = "K_MIDDLE"
constant K_INS = "K_INS"
constant K_DEL = "K_DEL"
constant K_sHOME = "K_sHOME"
constant K_sUP = "K_sUP"
constant K_sPGUP = "K_sPGUP"
constant K_sLEFT = "K_sLEFT"
constant K_sRIGHT = "K_sRIGHT"
constant K_sEND = "K_sEND"
constant K_sDOWN = "K_sDOWN"
constant K_sPGDN = "K_sPGDN"
constant K_cHOME = "K_cHOME"
constant K_cPGUP = "K_cPGUP"
constant K_cLEFT = "K_cLEFT"
constant K_cRIGHT = "K_cRIGHT"
constant K_cEND = "K_cEND"
constant K_cPGDN = "K_cPGDN"
constant K_cUP = "K_cUP"
constant K_cDOWN = "K_cDOWN"
constant K_cMIDDLE = "K_cMIDDLE"
constant K_cINS = "K_cINS"
constant K_cDEL = "K_cDEL"
constant K_mHOME = "K_mHOME"
constant K_mPGUP = "K_mPGUP"
constant K_mLEFT = "K_mLEFT"
constant K_mRIGHT = "K_mRIGHT"
constant K_mEND = "K_mEND"
constant K_mPGDN = "K_mPGDN"
constant K_mUP = "K_mUP"
constant K_mDOWN = "K_mDOWN"
constant K_mINS = "K_mINS"
constant K_mDEL = "K_mDEL"
constant K_F1 = "K_F1"
constant K_F2 = "K_F2"
constant K_F3 = "K_F3"
constant K_F4 = "K_F4"
constant K_F5 = "K_F5"
constant K_F6 = "K_F6"
constant K_F7 = "K_F7"
constant K_F8 = "K_F8"
constant K_F9 = "K_F9"
constant K_F10 = "K_F10"
constant K_F11 = "K_F11"
constant K_F12 = "K_F12"
constant K_sF1 = "K_sF1"
constant K_sF2 = "K_sF2"
constant K_sF3 = "K_sF3"
constant K_sF4 = "K_sF4"
constant K_sF5 = "K_sF5"
constant K_sF6 = "K_sF6"
constant K_sF7 = "K_sF7"
constant K_sF8 = "K_sF8"
constant K_sF9 = "K_sF9"
constant K_sF10 = "K_sF10"
constant K_sF11 = "K_sF11"
constant K_sF12 = "K_sF12"
constant K_cF1 = "K_cF1"
constant K_cF2 = "K_cF2"
constant K_cF3 = "K_cF3"
constant K_cF4 = "K_cF4"
constant K_cF5 = "K_cF5"
constant K_cF6 = "K_cF6"
constant K_cF7 = "K_cF7"
constant K_cF8 = "K_cF8"
constant K_cF9 = "K_cF9"
constant K_cF10 = "K_cF10"
constant K_cF11 = "K_cF11"
constant K_cF12 = "K_cF12"
constant K_mF1 = "K_mF1"
constant K_mF2 = "K_mF2"
constant K_mF3 = "K_mF3"
constant K_mF4 = "K_mF4"
constant K_mF5 = "K_mF5"
constant K_mF6 = "K_mF6"
constant K_mF7 = "K_mF7"
constant K_mF8 = "K_mF8"
constant K_mF9 = "K_mF9"
constant K_mF10 = "K_mF10"
constant K_m1 = "K_m1"
constant K_m2 = "K_m2"
constant K_m3 = "K_m3"
constant K_m4 = "K_m4"
constant K_m5 = "K_m5"
constant K_m6 = "K_m6"
constant K_m7 = "K_m7"
constant K_m8 = "K_m8"
constant K_m9 = "K_m9"
constant K_m0 = "K_m0"

##############
#  Colorbar  #
##############

constant NUM_PARTS = "NUM_PARTS"
constant NUM_CELLS = "NUM_CELLS"
constant CELL = "CELL"
constant PREVIEW_SIZE = "PREVIEW_SIZE"
constant SHOW_PREVIEW = "SHOW_PREVIEW"
constant SHOW_SECONDARY = "SHOW_SECONDARY"
constant PRIMARY_CELL = "PRIMARY_CELL"
constant SECONDARY_CELL = "SECONDARY_CELL"
constant ORIENTATION = "ORIENTATION"
constant SQUARED = "SQUARED"
constant SHADOWED = "SHADOWED"
constant BUFFERIZE = "BUFFERIZE"
constant TRANSPARENCY = "TRANSPARENCY"
constant CELL_CB = "CELL_CB"
constant EXTENDED_CB = "EXTENDED_CB"
constant SELECT_CB = "SELECT_CB"
constant SWITCH_CB = "SWITCH_CB"
constant VERTICAL = "VERTICAL"
constant HORIZONTAL = "HORIZONTAL"

##############
#  Cells     #
##############

constant ALL = "ALL"
constant BOXED = "BOXED"
constant CLIPPED = "CLIPPED"
constant TRANSPARENT = "TRANSPARENT"
constant NON_SCROLLABLE_LINES = "NON_SCROLLABLE_LINES"
constant NON_SCROLLABLE_COLS = "NON_SCROLLABLE_COLS"
constant ORIGIN = "ORIGIN"
constant NO_COLOR = "NO_COLOR"
constant FIRST_LINE = "FIRST_LINE"
constant FIRST_COL = "FIRST_COL"
constant DOUBLE_BUFFER = "DOUBLE_BUFFER"
constant LIMITS = "LIMITS"
constant CANVAS = "CANVAS"
constant IMAGE_CANVAS = "IMAGE_CANVAS"
constant FULL_VISIBLE = "FULL_VISIBLE"
constant MOUSECLICK_CB = "MOUSECLICK_CB"
constant MOUSEMOTION_CB = "MOUSEMOTION_CB"
constant DRAW_CB = "DRAW_CB"
constant WIDTH_CB = "WIDTH_CB"
constant HEIGHT_CB = "HEIGHT_CB"
constant NLINES_CB = "NLINES_CB"
constant NCOLS_CB = "NCOLS_CB"
constant HSPAN_CB = "HSPAN_CB"
constant VSPAN_CB = "VSPAN_CB"
constant SCROLLING_CB = "SCROLLING_CB"

###################
#  ColorBrowser   #
###################

constant RGB = "RGB"
constant CHANGE_CB = "CHANGE_CB"
constant DRAG_CB = "DRAG_CB"

###################
#  Val            #
###################

constant ICTL_MOUSEMOVE_CB = "MOUSEMOVE_CB"
constant ICTL_BUTTON_PRESS_CB = "BUTTON_PRESS_CB"
constant ICTL_BUTTON_RELEASE_CB = "BUTTON_RELEASE_CB"
constant ICTL_HORIZONTAL = "HORIZONTAL"
constant ICTL_VERTICAL = "VERTICAL"
constant ICTL_SHOWTICKS = "SHOWTICKS"

###################
#  Tabs           #
###################

constant ICTL_TOP = "TOP"
constant ICTL_BOTTOM = "BOTTOM"
constant ICTL_LEFT = "LEFT"
constant ICTL_RIGHT = "RIGHT"
constant ICTL_TABTYPE = "TABTYPE"
constant ICTL_TABTITLE = "TABTITLE"
constant ICTL_TABSIZE = "TABSIZE"
constant ICTL_TABCHANGE_CB = "TABCHANGE_CB"
constant ICTL_FONT = "FONT"
constant ICTL_FONT_ACTIVE = "FONT_ACTIVE"
constant ICTL_FONT_INACTIVE = "FONT_INACTIVE"

###################
#  Gauge          #
###################

constant ICTL_SHOW_TEXT = "SHOW_TEXT"
constant ICTL_DASHED = "DASHED"
constant ICTL_MARGIN = "MARGIN"
constant ICTL_TEXT = "TEXT"

###################
#  Dial           #
###################

constant ICTL_DENSITY = "DENSITY"
constant ICTL_HORIZONTAL = "HORIZONTAL"
constant ICTL_VERTICAL = "VERTICAL"
constant ICTL_CIRCULAR = "CIRCULAR"
constant ICTL_UNIT = "UNIT"

###################
#  Matrix         #
###################

constant ENTERITEM_CB = "ENTERITEM_CB"
constant LEAVEITEM_CB = "LEAVEITEM_CB"
constant EDITION_CB = "EDITION_CB"
constant CLICK_CB = "CLICK_CB"
constant DROP_CB = "DROP_CB"
constant DROPSELECT_CB = "DROPSELECT_CB"
constant DROPCHECK_CB = "DROPCHECK_CB"
constant SCROLL_CB = "SCROLL_CB"
constant VALUE_CB = "VALUE_CB"
constant VALUE_EDIT_CB = "VALUE_EDIT_CB"
constant FIELD_CB = "FIELD_CB"
constant RESIZEMATRIX = "RESIZEMATRIX"
constant ADDLIN = "ADDLIN"
constant ADDCOL = "ADDCOL"
constant DELLIN = "DELLIN"
constant DELCOL = "DELCOL"
constant NUMLIN = "NUMLIN"
constant NUMCOL = "NUMCOL"
constant NUMLIN_VISIBLE = "NUMLIN_VISIBLE"
constant NUMCOL_VISIBLE = "NUMCOL_VISIBLE"
constant MARKED = "MARKED"
constant WIDTHDEF = "WIDTHDEF"
constant HEIGHTDEF = "HEIGHTDEF"
constant AREA = "AREA"
constant MARK_MODE = "MARK_MODE"
constant LIN = "LIN"
constant COL = "COL"
constant LINCOL = "LINCOL"
constant CELL = "CELL"
constant EDIT_MODE = "EDIT_MODE"
constant FOCUS_CELL = "FOCUS_CELL"
constant ORIGIN = "ORIGIN"
constant REDRAW = "REDRAW"
constant PREVIOUSVALUE = "PREVIOUSVALUE"
constant MOUSEMOVE_CB = "MOUSEMOVE_CB"

###################
#  Tree           #
###################

constant ADDLEAF = "ADDLEAF"
constant ADDBRANCH = "ADDBRANCH"
constant DELNODE = "DELNODE"
constant IMAGELEAF = "IMAGELEAF"
constant IMAGEBRANCHCOLLAPSED = "IMAGEBRANCHCOLLAPSED"
constant IMAGEBRANCHEXPANDED = "IMAGEBRANCHEXPANDED"
constant IMAGEEXPANDED = "IMAGEEXPANDED"
constant KIND = "KIND"
constant PARENT = "PARENT"
constant DEPTH = "DEPTH"
constant MARKED = "MARKED"
constant ADDEXPANDED = "ADDEXPANDED"
constant CTRL = "CTRL"
constant SHIFT = "SHIFT"
constant STATE = "STATE"
constant STARTING = "STARTING"
constant LEAF = "LEAF"
constant BRANCH = "BRANCH"
constant SELECTED = "SELECTED"
constant CHILDREN = "CHILDREN"
constant MARKED = "MARKED"
constant ROOT = "ROOT"
constant LAST = "LAST"
constant PGUP = "PGUP"
constant PGDN = "PGDN"
constant NEXT = "NEXT"
constant PREVIOUS = "PREVIOUS"
constant INVERT = "INVERT"
constant BLOCK = "BLOCK"
constant CLEARALL = "CLEARALL"
constant MARKALL = "MARKALL"
constant INVERTALL = "INVERTALL"
constant REDRAW = "REDRAW"
constant COLLAPSED = "COLLAPSED"
constant EXPANDED = "EXPANDED"
constant SELECTION_CB = "SELECTION_CB"
constant BRANCHOPEN_CB = "BRANCHOPEN_CB"
constant BRANCHCLOSE_CB = "BRANCHCLOSE_CB"
constant RIGHTCLICK_CB = "RIGHTCLICK_CB"
constant EXECUTELEAF_CB = "EXECUTELEAF_CB"
constant RENAMENODE_CB = "RENAMENODE_CB"
constant IMGLEAF = "IMGLEAF"
constant IMGCOLLAPSED = "IMGCOLLAPSED"
constant IMGEXPANDED = "IMGEXPANDED"
constant IMGBLANK = "IMGBLANK"
constant IMGPAPER = "IMGPAPER"
